#!/bin/sh
#
# Start the network....
#

case "$1" in
  start)
	printf "Starting custom GPIO: "
	/usr/bin/blink
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping custom GPIO: "
	/usr/bin/blink stop
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

